# Generated by Django 2.1.1 on 2018-09-11 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='物资名称')),
                ('amount', models.IntegerField(verbose_name='总数')),
                ('restamount', models.IntegerField(verbose_name='剩余数量')),
                ('issupplies', models.CharField(max_length=5, verbose_name='是否为耗材')),
                ('image', models.ImageField(upload_to='assets/', verbose_name='参考图')),
                ('isstudio', models.CharField(max_length=5, verbose_name='是否为学校资产')),
                ('is_delete', models.IntegerField(default=0, verbose_name='是否被删除')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowmanage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='借阅数目')),
                ('starttime', models.CharField(blank=True, default=datetime.datetime(2018, 9, 11, 13, 5, 39, 151723, tzinfo=utc), max_length=15, verbose_name='借阅时间')),
                ('endtime', models.CharField(blank=True, max_length=15, verbose_name='归还时间')),
                ('borrowasset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sys5704.Asset', verbose_name='借阅物资')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='用户账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='姓名')),
                ('schoolid', models.CharField(blank=True, max_length=15, verbose_name='学生号')),
                ('sex', models.CharField(blank=True, max_length=5, verbose_name='性别')),
                ('birthday', models.CharField(blank=True, max_length=15, verbose_name='生日')),
                ('atschool', models.CharField(blank=True, max_length=5, verbose_name='是否在校')),
                ('major', models.CharField(blank=True, max_length=30, verbose_name='专业')),
                ('avatar', models.ImageField(blank=True, upload_to='users/', verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='电话')),
                ('qq', models.CharField(blank=True, max_length=15)),
                ('direction', models.CharField(blank=True, max_length=50, verbose_name='方向')),
                ('right', models.CharField(blank=True, max_length=10, verbose_name='权限')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('softwarepatent', models.CharField(blank=True, max_length=300, verbose_name='软件著作')),
                ('patent', models.CharField(blank=True, max_length=300, verbose_name='专利')),
                ('competition', models.CharField(blank=True, max_length=300, verbose_name='竞赛')),
                ('paper', models.CharField(blank=True, max_length=300, verbose_name='论文')),
                ('projects', models.CharField(blank=True, max_length=300, verbose_name='项目')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sys5704.User', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='borrowmanage',
            name='borrowuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sys5704.User', verbose_name='借阅人'),
        ),
    ]
