# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venvapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(blank=True, max_length=10, null=True)),
                ('symble', models.CharField(blank=True, max_length=10, null=True)),
                ('c_name', models.CharField(blank=True, max_length=10, null=True)),
                ('rela_weight', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('melt_point', models.CharField(blank=True, max_length=10, null=True)),
                ('boil_point', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.CharField(blank=True, max_length=10, null=True)),
                ('density', models.CharField(blank=True, max_length=10, null=True)),
                ('isotope', models.CharField(blank=True, max_length=10, null=True)),
                ('mo_body', models.CharField(blank=True, max_length=10, null=True)),
                ('ch_body', models.CharField(blank=True, max_length=10, null=True)),
                ('decay_e', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
