# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venvapp', '0002_hh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(blank=True, null=True)),
                ('symble', models.TextField(blank=True, null=True)),
                ('c_name', models.TextField(blank=True, null=True)),
                ('rela_weight', models.TextField(blank=True, null=True)),
                ('density', models.TextField(blank=True, null=True)),
                ('melt_point', models.TextField(blank=True, null=True)),
                ('boil_point', models.TextField(blank=True, null=True)),
                ('isotope_radioactivity', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Elem',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='HH',
        ),
    ]
