# Generated by Django 2.1.3 on 2018-12-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venvapp', '0004_fangse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elem',
            options={},
        ),
    ]
