# Generated by Django 2.1.3 on 2018-11-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('supplier', models.CharField(max_length=30, verbose_name='供应商')),
                ('add_time', models.CharField(max_length=30, verbose_name='入库时间')),
                ('inventory', models.CharField(max_length=30, verbose_name='库存')),
                ('unit_price', models.CharField(max_length=30, verbose_name='商品单价')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('object', models.CharField(max_length=30, verbose_name='销售对象')),
                ('contact', models.CharField(max_length=30, verbose_name='联系方式')),
                ('num', models.CharField(max_length=30, verbose_name='数量')),
                ('price', models.CharField(max_length=30, verbose_name='销售金额')),
                ('place', models.CharField(max_length=30, verbose_name='配送地点')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('supplier_name', models.CharField(max_length=30, verbose_name='代理商名称')),
                ('contact', models.CharField(max_length=30, verbose_name='联系方式')),
                ('num', models.CharField(max_length=30, verbose_name='数量')),
                ('price', models.CharField(max_length=30, verbose_name='商品价值')),
                ('time', models.CharField(max_length=30, verbose_name='出库时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=16, verbose_name='密码')),
            ],
        ),
    ]
