# Generated by Django 2.1.3 on 2018-11-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181125_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='add_time',
            field=models.CharField(blank=True, max_length=30, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='good',
            name='good_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='good',
            name='inventory',
            field=models.CharField(blank=True, max_length=30, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='good',
            name='supplier',
            field=models.CharField(blank=True, max_length=30, verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='good',
            name='unit_price',
            field=models.CharField(blank=True, max_length=30, verbose_name='商品单价'),
        ),
        migrations.AlterField(
            model_name='market',
            name='contact',
            field=models.CharField(blank=True, max_length=30, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='market',
            name='good_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='market',
            name='num',
            field=models.CharField(blank=True, max_length=30, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='market',
            name='object1',
            field=models.CharField(blank=True, max_length=30, verbose_name='销售对象'),
        ),
        migrations.AlterField(
            model_name='market',
            name='place',
            field=models.CharField(blank=True, max_length=30, verbose_name='配送地点'),
        ),
        migrations.AlterField(
            model_name='market',
            name='price',
            field=models.CharField(blank=True, max_length=30, verbose_name='销售金额'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=30, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='good_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='num',
            field=models.CharField(blank=True, max_length=30, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='price',
            field=models.CharField(blank=True, max_length=30, verbose_name='商品价值'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='代理商名称'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='time',
            field=models.CharField(blank=True, max_length=30, verbose_name='出库时间'),
        ),
    ]
